export interface Zone { code: string; name: string; country: string; }

export const ENTSO_ZONES: Zone[] = [
  { code: "DE",     name: "Germany",         country: "DE" },
  { code: "FR",     name: "France",          country: "FR" },
  { code: "NL",     name: "Netherlands",     country: "NL" },
  { code: "ES",     name: "Spain",           country: "ES" },
  { code: "AT",     name: "Austria",         country: "AT" },
  { code: "BE",     name: "Belgium",         country: "BE" },
  { code: "TR",     name: "Turkey",          country: "TR" },
  { code: "PL",     name: "Poland",          country: "PL" },
  { code: "NO",     name: "Norway",          country: "NO" },
  { code: "SE",     name: "Sweden",          country: "SE" },
  { code: "FI",     name: "Finland",         country: "FI" },
  { code: "CH",     name: "Switzerland",     country: "CH" },
  { code: "CZ",     name: "Czech Republic",  country: "CZ" },
  { code: "HU",     name: "Hungary",         country: "HU" },
  { code: "RO",     name: "Romania",         country: "RO" },
  { code: "SK",     name: "Slovakia",        country: "SK" },
  { code: "SI",     name: "Slovenia",        country: "SI" },
  { code: "HR",     name: "Croatia",         country: "HR" },
  { code: "BG",     name: "Bulgaria",        country: "BG" },
  { code: "GR",     name: "Greece",          country: "GR" },
  { code: "IT",     name: "Italy",           country: "IT" },
  { code: "PT",     name: "Portugal",        country: "PT" },
  { code: "DK-DK1", name: "Denmark West",   country: "DK" },
  { code: "DK-DK2", name: "Denmark East",   country: "DK" },
  { code: "LT",     name: "Lithuania",       country: "LT" },
  { code: "LV",     name: "Latvia",          country: "LV" },
  { code: "EE",     name: "Estonia",         country: "EE" },
  { code: "RS",     name: "Serbia",          country: "RS" },
  { code: "BA",     name: "Bosnia",          country: "BA" },
  { code: "ME",     name: "Montenegro",      country: "ME" },
  { code: "MK",     name: "North Macedonia", country: "MK" },
  { code: "AL",     name: "Albania",         country: "AL" },
];
